/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LedBlue.h
**     Project     : SetupSerialCommunication
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.066, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-03-13, 11:46, # CodeGen: 1
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LedBlue
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            Anode on port side, HIGH is ON               : no
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void LedBlue_Init(void);
**         Deinit     - void LedBlue_Deinit(void);
**         On         - void LedBlue_On(void);
**         Off        - void LedBlue_Off(void);
**         Neg        - void LedBlue_Neg(void);
**         Get        - uint8_t LedBlue_Get(void);
**         Put        - void LedBlue_Put(uint8_t val);
**         SetRatio16 - void LedBlue_SetRatio16(uint16_t ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013-2015, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LedBlue.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LedBlue_module LedBlue module documentation
**  @{
*/         

#ifndef __LedBlue_H
#define __LedBlue_H

/* MODULE LedBlue. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin3.h"

#include "Cpu.h"

#define LedBlue_ClrVal()    LEDpin3_ClrVal() /* put the pin on low level */
#define LedBlue_SetVal()    LEDpin3_SetVal() /* put the pin on high level */
#define LedBlue_SetInput()  LEDpin3_SetInput() /* use the pin as input pin */
#define LedBlue_SetOutput() LEDpin3_SetOutput() /* use the pin as output pin */

#define LedBlue_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define LedBlue_On() LEDpin3_ClrVal()
/*
** ===================================================================
**     Method      :  LedBlue_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LedBlue_Off() LEDpin3_SetVal()
/*
** ===================================================================
**     Method      :  LedBlue_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LedBlue_Neg() LEDpin3_NegVal()
/*
** ===================================================================
**     Method      :  LedBlue_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LedBlue_Get() (!(LEDpin3_GetVal()))
/*
** ===================================================================
**     Method      :  LedBlue_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define LedBlue_Init() LedBlue_Off()
/*
** ===================================================================
**     Method      :  LedBlue_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LedBlue_Put(val)  ((val) ? LedBlue_On() : LedBlue_Off())
/*
** ===================================================================
**     Method      :  LedBlue_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void LedBlue_Deinit(void);
/*
** ===================================================================
**     Method      :  LedBlue_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LedBlue_SetRatio16(uint16_t ratio);
/*
** ===================================================================
**     Method      :  LedBlue_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END LedBlue. */

#endif
/* ifndef __LedBlue_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
