/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LedRed.h
**     Project     : SetupSerialCommunication
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.066, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-03-13, 11:46, # CodeGen: 1
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LedRed
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            Anode on port side, HIGH is ON               : no
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void LedRed_Init(void);
**         Deinit     - void LedRed_Deinit(void);
**         On         - void LedRed_On(void);
**         Off        - void LedRed_Off(void);
**         Neg        - void LedRed_Neg(void);
**         Get        - uint8_t LedRed_Get(void);
**         Put        - void LedRed_Put(uint8_t val);
**         SetRatio16 - void LedRed_SetRatio16(uint16_t ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013-2015, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LedRed.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LedRed_module LedRed module documentation
**  @{
*/         

#ifndef __LedRed_H
#define __LedRed_H

/* MODULE LedRed. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin1.h"

#include "Cpu.h"

#define LedRed_ClrVal()    LEDpin1_ClrVal() /* put the pin on low level */
#define LedRed_SetVal()    LEDpin1_SetVal() /* put the pin on high level */
#define LedRed_SetInput()  LEDpin1_SetInput() /* use the pin as input pin */
#define LedRed_SetOutput() LEDpin1_SetOutput() /* use the pin as output pin */

#define LedRed_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define LedRed_On() LEDpin1_ClrVal()
/*
** ===================================================================
**     Method      :  LedRed_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LedRed_Off() LEDpin1_SetVal()
/*
** ===================================================================
**     Method      :  LedRed_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LedRed_Neg() LEDpin1_NegVal()
/*
** ===================================================================
**     Method      :  LedRed_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LedRed_Get() (!(LEDpin1_GetVal()))
/*
** ===================================================================
**     Method      :  LedRed_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define LedRed_Init() LedRed_Off()
/*
** ===================================================================
**     Method      :  LedRed_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LedRed_Put(val)  ((val) ? LedRed_On() : LedRed_Off())
/*
** ===================================================================
**     Method      :  LedRed_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void LedRed_Deinit(void);
/*
** ===================================================================
**     Method      :  LedRed_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LedRed_SetRatio16(uint16_t ratio);
/*
** ===================================================================
**     Method      :  LedRed_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END LedRed. */

#endif
/* ifndef __LedRed_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
