/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : I2C0.c
**     Project     : FreedomProjekt1
**     Processor   : MKL25Z128VLK4
**     Component   : Init_I2C
**     Version     : Component 01.008, Driver 01.08, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-03-09, 16:30, # CodeGen: 2
**     Abstract    :
**          This file implements the I2C (I2C0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : I2C0
**          Device                                         : I2C0
**          Settings                                       : 
**            Clock gate                                   : Do not initialize
**            Clock setting                                : 
**              Multiplier factor                          : divide by 1
**              Clock rate                                 : 0
**              SCL frequency                              : 1.049 MHz
**              SDA hold value                             : 0.334 us
**              Slave baud rate control                    : Disabled
**              SCL low timeout counter clock select       : Bus clock/64
**              SCL low timout counter                     : 0
**              SCL low timeout                            : STOP
**            General call address                         : Disabled
**            Address mode                                 : 7-bit addressing
**            Slave address                                : 0
**            Transfer direction                           : Receive
**            Transmit Acknowledge                         : yes
**            Fast acknowledge                             : Disabled
**            Wake-up                                      : Disabled
**            Noise (glitch) filter factor                 : 0
**            Alert response address                       : Disabled
**            Second address                               : Disabled
**            Second address value                         : 97
**            Range address matching                       : Disabled
**            Range address                                : 0
**            Stop hold                                    : Disabled
**          Pins                                           : 
**            SDA pin allocation                           : Enabled
**              SDA pin                                    : PTE25/TPM0_CH1/I2C0_SDA
**              SDA pin signal                             : 
**            SCL pin allocation                           : Enabled
**              SCL pin                                    : PTE24/TPM0_CH0/I2C0_SCL
**              SCL pin signal                             : 
**            High drive select                            : Disabled
**          Interrupts/DMA                                 : 
**            I2C interrupt/DMA                            : 
**              Interrupt                                  : INT_I2C0
**              Interrupt request                          : Disabled
**              Interrupt priority                         : 0 (Highest)
**              ISR Name                                   : 
**              I2C interrupt request                      : Disabled
**              SDA low, SCL high timeout interrupt        : Disabled
**              Bus stop interrupt                         : Disabled
**              I2C request type                           : Interrupt
**          Initialization                                 : 
**            Module enable                                : no
**            Master/Slave mode select                     : Slave
**            Call Init method                             : yes
**     Contents    :
**         Init - void I2C0_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file I2C0.c
** @version 01.08
** @brief
**          This file implements the I2C (I2C0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup I2C0_module I2C0 module documentation
**  @{
*/         

/* MODULE I2C0. */

#include "I2C0.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  I2C0_Init (component Init_I2C)
**     Description :
**         This method initializes registers of the I2C module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void I2C0_Init(void)
{
  /* I2C0_FLT: SHEN=0,STOPF=0,STOPIE=0,FLT=0 */
  I2C0_FLT = I2C_FLT_FLT(0x00);
  /* I2C0_A1: AD=0,??=0 */
  I2C0_A1 = I2C_A1_AD(0x00);
  /* I2C0_C2: GCAEN=0,ADEXT=0,HDRS=0,SBRC=0,RMEN=0,AD=0 */
  I2C0_C2 = I2C_C2_AD(0x00);
  /* I2C0_RA: RAD=0,??=0 */
  I2C0_RA = I2C_RA_RAD(0x00);
  /* I2C0_F: MULT=0,ICR=0 */
  I2C0_F = (I2C_F_MULT(0x00) | I2C_F_ICR(0x00));
  /* I2C0_A2: SAD=0x61,??=0 */
  I2C0_A2 = I2C_A2_SAD(0x61);
  /* I2C0_SMB: FACK=0,ALERTEN=0,SIICAEN=0,TCKSEL=0,SLTF=1,SHTF1=0,SHTF2=1,SHTF2IE=0 */
  I2C0_SMB = (I2C_SMB_SLTF_MASK | I2C_SMB_SHTF2_MASK);
  /* I2C0_SLTH: SSLT=0 */
  I2C0_SLTH = I2C_SLTH_SSLT(0x00);
  /* I2C0_SLTL: SSLT=0 */
  I2C0_SLTL = I2C_SLTL_SSLT(0x00);
  /* I2C0_S: TCF=0,IAAS=0,BUSY=0,ARBL=1,RAM=0,SRW=0,IICIF=1,RXAK=0 */
  I2C0_S = (I2C_S_ARBL_MASK | I2C_S_IICIF_MASK);
  /* I2C0_C1: IICEN=0,IICIE=0,MST=0,TX=0,TXAK=0,RSTA=0,WUEN=0,DMAEN=0 */
  I2C0_C1 = 0x00U;
}


/* END I2C0. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
