/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : I2C0.h
**     Project     : FreedomProjekt1
**     Processor   : MKL25Z128VLK4
**     Component   : Init_I2C
**     Version     : Component 01.008, Driver 01.08, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-03-09, 16:30, # CodeGen: 2
**     Abstract    :
**          This file implements the I2C (I2C0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : I2C0
**          Device                                         : I2C0
**          Settings                                       : 
**            Clock gate                                   : Do not initialize
**            Clock setting                                : 
**              Multiplier factor                          : divide by 1
**              Clock rate                                 : 0
**              SCL frequency                              : 1.049 MHz
**              SDA hold value                             : 0.334 us
**              Slave baud rate control                    : Disabled
**              SCL low timeout counter clock select       : Bus clock/64
**              SCL low timout counter                     : 0
**              SCL low timeout                            : STOP
**            General call address                         : Disabled
**            Address mode                                 : 7-bit addressing
**            Slave address                                : 0
**            Transfer direction                           : Receive
**            Transmit Acknowledge                         : yes
**            Fast acknowledge                             : Disabled
**            Wake-up                                      : Disabled
**            Noise (glitch) filter factor                 : 0
**            Alert response address                       : Disabled
**            Second address                               : Disabled
**            Second address value                         : 97
**            Range address matching                       : Disabled
**            Range address                                : 0
**            Stop hold                                    : Disabled
**          Pins                                           : 
**            SDA pin allocation                           : Enabled
**              SDA pin                                    : PTE25/TPM0_CH1/I2C0_SDA
**              SDA pin signal                             : 
**            SCL pin allocation                           : Enabled
**              SCL pin                                    : PTE24/TPM0_CH0/I2C0_SCL
**              SCL pin signal                             : 
**            High drive select                            : Disabled
**          Interrupts/DMA                                 : 
**            I2C interrupt/DMA                            : 
**              Interrupt                                  : INT_I2C0
**              Interrupt request                          : Disabled
**              Interrupt priority                         : 0 (Highest)
**              ISR Name                                   : 
**              I2C interrupt request                      : Disabled
**              SDA low, SCL high timeout interrupt        : Disabled
**              Bus stop interrupt                         : Disabled
**              I2C request type                           : Interrupt
**          Initialization                                 : 
**            Module enable                                : no
**            Master/Slave mode select                     : Slave
**            Call Init method                             : yes
**     Contents    :
**         Init - void I2C0_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file I2C0.h
** @version 01.08
** @brief
**          This file implements the I2C (I2C0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup I2C0_module I2C0 module documentation
**  @{
*/         

#ifndef I2C0_H_
#define I2C0_H_

/* MODULE I2C0. */

/* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

/* Peripheral base address parameter */
#define I2C0_DEVICE I2C0_BASE_PTR


/*
** ===================================================================
**     Method      :  I2C0_Init (component Init_I2C)
**     Description :
**         This method initializes registers of the I2C module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void I2C0_Init(void);


/* END I2C0. */
#endif /* #ifndef __I2C0_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
